package vista;

import controlador.ControladorEstadoCivil;
import controlador.ControladorFuncionario;
import controlador.ControladorTipoIdentificacion;
import dao.EstadoCivilDAO;
import dao.EstadoCivilDAOimpl;
import dao.FuncionarioDAO;
import dao.FuncionarioDAOimpl;
import dao.TipoIdentificacionDAO;
import dao.TipoIdentificacionDAOimpl;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import modelo.EstadoCivil;
import modelo.Funcionario;
import modelo.TipoIdentificacion;
import utils.Mensajes;

/**
 *
 * @author Anderson Londoño
 */
public class Front extends javax.swing.JFrame {

    private ControladorTipoIdentificacion controladorTipoIdentificacion;
    private ControladorEstadoCivil controladorEstadoCivil;
    private ControladorFuncionario controladorFuncionarios;

    public Front() {
        initComponents();
        llenarSelectTipoDoc();
        llenarSelectEstadoCivil();
        llenarTablaFuncionarios();
        desactivarCajas();
    }

    private void llenarSelectTipoDoc() {
        TipoIdentificacionDAO identificacionDAO = new TipoIdentificacionDAOimpl();
        controladorTipoIdentificacion = new ControladorTipoIdentificacion(identificacionDAO);
        cbox_tipoId.setModel(controladorTipoIdentificacion.llenarSelectTipoIdentificacion());
    }

    private void llenarSelectEstadoCivil() {
        EstadoCivilDAO estadoCivilDAO = new EstadoCivilDAOimpl();
        controladorEstadoCivil = new ControladorEstadoCivil(estadoCivilDAO);
        cbox_estadoCivil.setModel(controladorEstadoCivil.llenarSelectEstadoCivil());
    }

    private void llenarTablaFuncionarios() {
        FuncionarioDAO funcionarioDao = new FuncionarioDAOimpl();
        controladorFuncionarios = new ControladorFuncionario(funcionarioDao);
        tabla_funcionarios.setModel(controladorFuncionarios.llenarTabla());
    }
    
    private void activarCajas(){
        btn_agregar.setEnabled(true);
        
    } 
    
    private void desactivarCajas(){
        btn_eliminar.setEnabled(false);
        btn_actualizar.setEnabled(false);
    } 
    
    private void limpiarTXT(){
    
        txt_documento.setText("");
            txt_nombre.setText("");
            txt_apellidos.setText("");
            txt_sexo.setText("");
            txt_direccion.setText("");
            txt_telefono.setText("");
            dchooser_fechaNacimiento.setToolTipText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_documento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbox_tipoId = new javax.swing.JComboBox<>();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbox_estadoCivil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_sexo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dchooser_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        btn_agregar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_funcionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Documento :");

        txt_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_documentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo ID : ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText(" FUNCIONARIOS");

        jLabel4.setText("Nombre :");

        cbox_tipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Cedula Ciudadania", "Cedula Extranjeria", "Registro Civil", " " }));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellidos :");

        jLabel6.setText("Estado Civil :");

        cbox_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Soltero", "Union Libre", "Casado", "Viudo" }));

        jLabel7.setText("Sexo :");

        jLabel8.setText("Direccion :");

        jLabel9.setText("Telefono :");

        jLabel10.setText("Fecha Nacimiento :");

        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tabla_funcionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombres", "Apellidos", "Sexo", "Direccion", "Telefono", "Fecha Nacimiento"
            }
        ));
        tabla_funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_funcionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_funcionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbox_tipoId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_documento)
                    .addComponent(txt_nombre)
                    .addComponent(txt_apellidos))
                .addGap(18, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dchooser_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_actualizar)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbox_tipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbox_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10))
                    .addComponent(dchooser_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualizar)
                            .addComponent(btn_agregar))
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documentoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed

        Funcionario funcionario = new Funcionario();
        TipoIdentificacion tipoIdentificacion = new TipoIdentificacion(cbox_tipoId.getSelectedIndex() + 1);
        EstadoCivil estadoCivil = new EstadoCivil(cbox_estadoCivil.getSelectedIndex() + 1);

        funcionario.setTipoIdentificacion(tipoIdentificacion);
        funcionario.setDocumento(Integer.parseInt(txt_documento.getText().trim()));
        funcionario.setNombre(txt_nombre.getText());
        funcionario.setApellido(txt_apellidos.getText());
        funcionario.setEstadoCivil(estadoCivil);
        funcionario.setSexo(txt_sexo.getText());
        funcionario.setDireccion(txt_direccion.getText());
        funcionario.setTelefono(txt_telefono.getText());
        if (dchooser_fechaNacimiento.getDate() != null) {

            funcionario.setFechaNacimiento(dchooser_fechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        } else {
            funcionario.setFechaNacimiento(LocalDate.now(ZoneId.systemDefault()));
        }

        controladorFuncionarios.guardarFuncionario(funcionario);

        llenarTablaFuncionarios();
        desactivarCajas();
        limpiarTXT();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int fila = tabla_funcionarios.getSelectedRow(); //formulario.tblDatos.getSelectedRow();
        if (fila == -1 ) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Funcionario o ingresar el Documento");
        } else {
            btn_eliminar.setEnabled(true);

            if (Mensajes.mensajeConfirmacion("Eliminar Usuario", "Esta seguro en eliminar el usuario")) {
               
                int  id_doc = Integer.parseInt((String) tabla_funcionarios.getValueAt(fila, 0).toString());
                    controladorFuncionarios.borrar(id_doc);

            }
        }

        llenarTablaFuncionarios();
        activarCajas();
        desactivarCajas();
        limpiarTXT();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Funcionario funcionario = new Funcionario();
        TipoIdentificacion tipoIdentificacion = new TipoIdentificacion(cbox_tipoId.getSelectedIndex() + 1);
        EstadoCivil estadoCivil = new EstadoCivil(cbox_estadoCivil.getSelectedIndex() + 1);

        funcionario.setTipoIdentificacion(tipoIdentificacion);
        funcionario.setDocumento(Integer.parseInt(txt_documento.getText().trim()));
        funcionario.setNombre(txt_nombre.getText());
        funcionario.setApellido(txt_apellidos.getText());
        funcionario.setEstadoCivil(estadoCivil);
        funcionario.setSexo(txt_sexo.getText());
        funcionario.setDireccion(txt_direccion.getText());
        funcionario.setTelefono(txt_telefono.getText());
        if (dchooser_fechaNacimiento.getDate() != null) {

            funcionario.setFechaNacimiento(dchooser_fechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        } else {
            funcionario.setFechaNacimiento(LocalDate.now(ZoneId.systemDefault()));
        }
        
        
        controladorFuncionarios.actualizar(funcionario);
        llenarTablaFuncionarios();
        activarCajas();
        desactivarCajas();
        limpiarTXT();
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void tabla_funcionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_funcionariosMouseClicked
        if(tabla_funcionarios.getSelectedRow() != -1){
            btn_eliminar.setEnabled(true);
            btn_actualizar.setEnabled(true);
            btn_agregar.setEnabled(false);
            
            int fila = tabla_funcionarios.getSelectedRow();
            
            txt_documento.setText(tabla_funcionarios.getValueAt(fila, 0).toString());
            txt_nombre.setText(tabla_funcionarios.getValueAt(fila, 1).toString());
            txt_apellidos.setText(tabla_funcionarios.getValueAt(fila, 2).toString());
            txt_sexo.setText(tabla_funcionarios.getValueAt(fila, 3).toString());
            txt_direccion.setText(tabla_funcionarios.getValueAt(fila, 4).toString());
            txt_telefono.setText(tabla_funcionarios.getValueAt(fila, 5).toString());
            dchooser_fechaNacimiento.setToolTipText(tabla_funcionarios.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_tabla_funcionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> cbox_estadoCivil;
    private javax.swing.JComboBox<String> cbox_tipoId;
    private com.toedter.calendar.JDateChooser dchooser_fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_funcionarios;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_documento;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_sexo;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
